name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Show pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Build
        run: pnpm -r build

      - name: Test
        run: pnpm -r test
